name: Ubuntu 

on: [push, pull_request]

jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.14.1
      - name: Use cmake
        run: |
          cmake -B build
          cmake --build build
